USE cloud_master;

-- Table for Voicemail
CREATE TABLE IF NOT EXISTS voicemail (
    uniqueid INT(11) NOT NULL AUTO_INCREMENT,
    context VARCHAR(80) NOT NULL DEFAULT 'default',
    mailbox VARCHAR(80) NOT NULL,
    password VARCHAR(80) NOT NULL,
    fullname VARCHAR(80) DEFAULT NULL,
    alias VARCHAR(80) DEFAULT NULL,
    email VARCHAR(80) DEFAULT NULL,
    pager VARCHAR(80) DEFAULT NULL,
    attach VARCHAR(3) DEFAULT 'yes',
    saycid VARCHAR(3) DEFAULT 'yes',
    sayduration VARCHAR(3) DEFAULT 'no',
    saydurationm INT(11) DEFAULT '1',
    sendvoicemail VARCHAR(3) DEFAULT 'no',
    review VARCHAR(3) DEFAULT 'no',
    tempgreetwarn VARCHAR(3) DEFAULT 'no',
    operator VARCHAR(3) DEFAULT 'no',
    envelope VARCHAR(3) DEFAULT 'no',
    saydatetime VARCHAR(3) DEFAULT 'yes',
    tz VARCHAR(10) DEFAULT 'central24',
    deletevoicemail VARCHAR(3) DEFAULT 'no',
    volgain VARCHAR(4) DEFAULT '0.0',
    hidefromdir VARCHAR(3) DEFAULT 'yes',
    imapuser VARCHAR(80) DEFAULT NULL,
    imappassword VARCHAR(80) DEFAULT NULL,
    imapserver VARCHAR(80) DEFAULT NULL,
    imapport VARCHAR(80) DEFAULT NULL,
    imapflags VARCHAR(80) DEFAULT NULL,
    stamp datetime DEFAULT NULL,
    PRIMARY KEY (uniqueid),
    KEY mailbox (mailbox),
    KEY context (context)
);

-- Table for Queues
CREATE TABLE IF NOT EXISTS queues (
    name VARCHAR(128) NOT NULL,
    musiconhold VARCHAR(128) DEFAULT NULL,
    announce VARCHAR(128) DEFAULT NULL,
    context VARCHAR(128) DEFAULT NULL,
    timeout INT(11) DEFAULT NULL,
    monitor_join VARCHAR(3) DEFAULT NULL,
    monitor_format VARCHAR(128) DEFAULT NULL,
    queue_youarenext VARCHAR(128) DEFAULT NULL,
    queue_thereare VARCHAR(128) DEFAULT NULL,
    queue_calls VARCHAR(128) DEFAULT NULL,
    queue_holdtime VARCHAR(128) DEFAULT NULL,
    queue_minutes VARCHAR(128) DEFAULT NULL,
    queue_seconds VARCHAR(128) DEFAULT NULL,
    queue_lessthan VARCHAR(128) DEFAULT NULL,
    queue_thankyou VARCHAR(128) DEFAULT NULL,
    queue_reporthold VARCHAR(128) DEFAULT NULL,
    announce_frequency INT(11) DEFAULT NULL,
    announce_round_seconds INT(11) DEFAULT NULL,
    announce_holdtime VARCHAR(128) DEFAULT NULL,
    retry INT(11) DEFAULT NULL,
    wrapuptime INT(11) DEFAULT NULL,
    maxlen INT(11) DEFAULT NULL,
    servicelevel INT(11) DEFAULT NULL,
    strategy VARCHAR(128) DEFAULT NULL,
    joinempty VARCHAR(128) DEFAULT NULL,
    leavewhenempty VARCHAR(128) DEFAULT NULL,
    eventmemberstatus VARCHAR(3) DEFAULT NULL,
    eventwhencalled VARCHAR(3) DEFAULT NULL,
    reportholdtime VARCHAR(3) DEFAULT NULL,
    memberdelay INT(11) DEFAULT NULL,
    weight INT(11) DEFAULT NULL,
    timeoutrestart VARCHAR(3) DEFAULT NULL,
    periodic_announce VARCHAR(128) DEFAULT NULL,
    periodic_announce_frequency INT(11) DEFAULT NULL,
    ringinuse VARCHAR(3) DEFAULT NULL,
    setinterfacevar VARCHAR(3) DEFAULT NULL,
    PRIMARY KEY (name)
);

-- Table for Queue Members
CREATE TABLE IF NOT EXISTS queue_members (
    uniqueid INT(11) NOT NULL AUTO_INCREMENT,
    queue_name VARCHAR(128) NOT NULL,
    interface VARCHAR(128) NOT NULL,
    membername VARCHAR(128) DEFAULT NULL,
    state_interface VARCHAR(128) DEFAULT NULL,
    penalty INT(11) DEFAULT NULL,
    paused INT(11) DEFAULT NULL,
    PRIMARY KEY (uniqueid),
    UNIQUE KEY queue_name_interface (queue_name, interface)
);
