-- ========================================
-- PUC Colombia Completo para CloudFly
-- Plan Único de Cuentas - Colombia
-- ========================================

-- Limpiar y recrear con INSERT IGNORE para no duplicar
-- (No borra datos existentes, solo agrega faltantes)

-- =====================
-- CLASE 1: ACTIVO
-- =====================
INSERT IGNORE INTO chart_of_accounts (code, name, account_type, level, parent_code, nature, requires_third_party, requires_cost_center, is_active, is_system, created_at, updated_at) VALUES
('1', 'ACTIVO', 'ACTIVO', 1, NULL, 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('11', 'DISPONIBLE', 'ACTIVO', 2, '1', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('1105', 'CAJA', 'ACTIVO', 4, '11', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('110505', 'CAJA GENERAL', 'ACTIVO', 6, '1105', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('110510', 'CAJAS MENORES', 'ACTIVO', 6, '1105', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('1110', 'BANCOS', 'ACTIVO', 4, '11', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('111005', 'BANCOS NACIONALES', 'ACTIVO', 6, '1110', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('111010', 'BANCOS EXTRANJEROS', 'ACTIVO', 6, '1110', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('13', 'DEUDORES', 'ACTIVO', 2, '1', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('1305', 'CLIENTES', 'ACTIVO', 4, '13', 'DEBITO', TRUE, FALSE, TRUE, TRUE, NOW(), NOW()),
('130505', 'CLIENTES NACIONALES', 'ACTIVO', 6, '1305', 'DEBITO', TRUE, FALSE, TRUE, TRUE, NOW(), NOW()),
('1355', 'ANTICIPO DE IMPUESTOS', 'ACTIVO', 4, '13', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('14', 'INVENTARIOS', 'ACTIVO', 2, '1', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('1435', 'MERCANCIAS NO FABRICADAS', 'ACTIVO', 4, '14', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('15', 'PROPIEDADES PLANTA Y EQUIPO', 'ACTIVO', 2, '1', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('1524', 'EQUIPO DE OFICINA', 'ACTIVO', 4, '15', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('1528', 'EQUIPO DE COMPUTACION', 'ACTIVO', 4, '15', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW());

-- =====================
-- CLASE 2: PASIVO
-- =====================
INSERT IGNORE INTO chart_of_accounts (code, name, account_type, level, parent_code, nature, requires_third_party, requires_cost_center, is_active, is_system, created_at, updated_at) VALUES
('2', 'PASIVO', 'PASIVO', 1, NULL, 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('22', 'PROVEEDORES', 'PASIVO', 2, '2', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2205', 'PROVEEDORES NACIONALES', 'PASIVO', 4, '22', 'CREDITO', TRUE, FALSE, TRUE, TRUE, NOW(), NOW()),
('23', 'CUENTAS POR PAGAR', 'PASIVO', 2, '2', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2335', 'COSTOS Y GASTOS POR PAGAR', 'PASIVO', 4, '23', 'CREDITO', TRUE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2365', 'RETENCION EN LA FUENTE', 'PASIVO', 4, '23', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2367', 'RETENCION ICA', 'PASIVO', 4, '23', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2368', 'RETENCION IVA', 'PASIVO', 4, '23', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2370', 'RETENCIONES Y APORTES DE NOMINA', 'PASIVO', 4, '23', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('237005', 'APORTES EPS', 'PASIVO', 6, '2370', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('237006', 'APORTES ARL', 'PASIVO', 6, '2370', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('237010', 'APORTES CAJA COMPENSACION', 'PASIVO', 6, '2370', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('237025', 'FONDOS DE CESANTIAS', 'PASIVO', 6, '2370', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('237030', 'APORTES ICBF', 'PASIVO', 6, '2370', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('237040', 'APORTES SENA', 'PASIVO', 6, '2370', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2380', 'ACREEDORES VARIOS', 'PASIVO', 4, '23', 'CREDITO', TRUE, FALSE, TRUE, TRUE, NOW(), NOW()),
('238030', 'FONDOS DE PENSIONES', 'PASIVO', 6, '2380', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('24', 'IMPUESTOS GRAVAMENES Y TASAS', 'PASIVO', 2, '2', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2408', 'IVA POR PAGAR', 'PASIVO', 4, '24', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('240802', 'IVA 5%', 'PASIVO', 6, '2408', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('240803', 'IVA 19%', 'PASIVO', 6, '2408', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('25', 'OBLIGACIONES LABORALES', 'PASIVO', 2, '2', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2505', 'SALARIOS POR PAGAR', 'PASIVO', 4, '25', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('250501', 'SUELDOS Y SALARIOS', 'PASIVO', 6, '2505', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2510', 'CESANTIAS CONSOLIDADAS', 'PASIVO', 4, '25', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2515', 'INTERESES SOBRE CESANTIAS', 'PASIVO', 4, '25', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2520', 'PRIMA DE SERVICIOS', 'PASIVO', 4, '25', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2525', 'VACACIONES CONSOLIDADAS', 'PASIVO', 4, '25', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('26', 'PASIVOS ESTIMADOS Y PROVISIONES', 'PASIVO', 2, '2', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('2610', 'PARA OBLIGACIONES LABORALES', 'PASIVO', 4, '26', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('261005', 'CESANTIAS', 'PASIVO', 6, '2610', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('261010', 'INTERESES CESANTIAS', 'PASIVO', 6, '2610', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('261015', 'VACACIONES', 'PASIVO', 6, '2610', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('261020', 'PRIMA DE SERVICIOS', 'PASIVO', 6, '2610', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW());

-- =====================
-- CLASE 3: PATRIMONIO
-- =====================
INSERT IGNORE INTO chart_of_accounts (code, name, account_type, level, parent_code, nature, requires_third_party, requires_cost_center, is_active, is_system, created_at, updated_at) VALUES
('3', 'PATRIMONIO', 'PATRIMONIO', 1, NULL, 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('31', 'CAPITAL SOCIAL', 'PATRIMONIO', 2, '3', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('3105', 'CAPITAL SUSCRITO Y PAGADO', 'PATRIMONIO', 4, '31', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('36', 'RESULTADOS DEL EJERCICIO', 'PATRIMONIO', 2, '3', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('3605', 'UTILIDAD DEL EJERCICIO', 'PATRIMONIO', 4, '36', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('3610', 'PERDIDA DEL EJERCICIO', 'PATRIMONIO', 4, '36', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('37', 'RESULTADOS EJERCICIOS ANTERIORES', 'PATRIMONIO', 2, '3', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('3705', 'UTILIDADES ACUMULADAS', 'PATRIMONIO', 4, '37', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('3710', 'PERDIDAS ACUMULADAS', 'PATRIMONIO', 4, '37', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW());

-- =====================
-- CLASE 4: INGRESOS
-- =====================
INSERT IGNORE INTO chart_of_accounts (code, name, account_type, level, parent_code, nature, requires_third_party, requires_cost_center, is_active, is_system, created_at, updated_at) VALUES
('4', 'INGRESOS', 'INGRESO', 1, NULL, 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('41', 'OPERACIONALES', 'INGRESO', 2, '4', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('4135', 'COMERCIO AL POR MAYOR Y MENOR', 'INGRESO', 4, '41', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('413505', 'VENTAS GRAVADAS', 'INGRESO', 6, '4135', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('413510', 'VENTAS EXENTAS', 'INGRESO', 6, '4135', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('4175', 'DEVOLUCIONES EN VENTAS', 'INGRESO', 4, '41', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('42', 'NO OPERACIONALES', 'INGRESO', 2, '4', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('4210', 'FINANCIEROS', 'INGRESO', 4, '42', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('4295', 'DIVERSOS', 'INGRESO', 4, '42', 'CREDITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW());

-- =====================
-- CLASE 5: GASTOS
-- =====================
INSERT IGNORE INTO chart_of_accounts (code, name, account_type, level, parent_code, nature, requires_third_party, requires_cost_center, is_active, is_system, created_at, updated_at) VALUES
('5', 'GASTOS', 'GASTO', 1, NULL, 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('51', 'OPERACIONALES DE ADMINISTRACION', 'GASTO', 2, '5', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('5105', 'GASTOS DE PERSONAL', 'GASTO', 4, '51', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510506', 'SUELDOS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510515', 'HORAS EXTRAS Y RECARGOS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510518', 'COMISIONES', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510521', 'VIÁTICOS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510524', 'INCAPACIDADES', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510527', 'AUXILIO DE TRANSPORTE', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510530', 'CESANTIAS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510533', 'INTERESES SOBRE CESANTIAS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510536', 'PRIMA DE SERVICIOS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510539', 'VACACIONES', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510542', 'PRIMAS EXTRALEGALES', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510545', 'AUXILIOS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510548', 'BONIFICACIONES', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510551', 'DOTACION Y SUMINISTRO', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510568', 'APORTES ARL', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510569', 'APORTES EPS', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510570', 'APORTES FONDOS DE PENSIONES', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510572', 'APORTES CAJAS DE COMPENSACION', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510575', 'APORTES ICBF', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('510578', 'APORTES SENA', 'GASTO', 6, '5105', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('5110', 'HONORARIOS', 'GASTO', 4, '51', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('5115', 'IMPUESTOS', 'GASTO', 4, '51', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('511505', 'INDUSTRIA Y COMERCIO', 'GASTO', 6, '5115', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('5120', 'ARRENDAMIENTOS', 'GASTO', 4, '51', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('512005', 'TERRENOS', 'GASTO', 6, '5120', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('512010', 'CONSTRUCCIONES Y EDIFICACIONES', 'GASTO', 6, '5120', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('5135', 'SERVICIOS', 'GASTO', 4, '51', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513505', 'ASEO Y VIGILANCIA', 'GASTO', 6, '5135', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513525', 'ACUEDUCTO Y ALCANTARILLADO', 'GASTO', 6, '5135', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513530', 'ENERGIA ELECTRICA', 'GASTO', 6, '5135', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513535', 'TELEFONO', 'GASTO', 6, '5135', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513540', 'CORREO PORTES Y TELEGRAMAS', 'GASTO', 6, '5135', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513545', 'FAX Y TÉLEX', 'GASTO', 6, '5135', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513550', 'TRANSPORTE FLETES Y ACARREOS', 'GASTO', 6, '5135', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('513595', 'OTROS SERVICIOS', 'GASTO', 6, '5135', 'DEBITO', TRUE, TRUE, TRUE, TRUE, NOW(), NOW()),
('5195', 'DIVERSOS', 'GASTO', 4, '51', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('519595', 'OTROS', 'GASTO', 6, '5195', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('52', 'OPERACIONALES DE VENTAS', 'GASTO', 2, '5', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('5205', 'GASTOS DE PERSONAL VENTAS', 'GASTO', 4, '52', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('520506', 'SUELDOS VENTAS', 'GASTO', 6, '5205', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('520518', 'COMISIONES VENTAS', 'GASTO', 6, '5205', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('53', 'NO OPERACIONALES', 'GASTO', 2, '5', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('5305', 'FINANCIEROS', 'GASTO', 4, '53', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('530505', 'GASTOS BANCARIOS', 'GASTO', 6, '5305', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('530515', 'COMISIONES', 'GASTO', 6, '5305', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('530520', 'INTERESES', 'GASTO', 6, '5305', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('5395', 'GASTOS EXTRAORDINARIOS', 'GASTO', 4, '53', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW());

-- =====================
-- CLASE 6: COSTOS DE VENTAS
-- =====================
INSERT IGNORE INTO chart_of_accounts (code, name, account_type, level, parent_code, nature, requires_third_party, requires_cost_center, is_active, is_system, created_at, updated_at) VALUES
('6', 'COSTOS DE VENTAS', 'COSTO', 1, NULL, 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('61', 'COSTO DE VENTAS', 'COSTO', 2, '6', 'DEBITO', FALSE, FALSE, TRUE, TRUE, NOW(), NOW()),
('6135', 'COMERCIO AL POR MAYOR Y MENOR', 'COSTO', 4, '61', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW()),
('613505', 'COSTO MERCANCIAS VENDIDAS', 'COSTO', 6, '6135', 'DEBITO', FALSE, TRUE, TRUE, TRUE, NOW(), NOW());

-- =====================
-- VERIFICACION
-- =====================
SELECT account_type AS 'Clase', COUNT(*) AS 'Cuentas' FROM chart_of_accounts GROUP BY account_type ORDER BY account_type;
SELECT CONCAT('Total cuentas PUC: ', COUNT(*)) AS 'Resultado' FROM chart_of_accounts;
