spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:cloud_master}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:widowmaker}
  main:
    web-application-type: reactive
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
    io.asyncer.r2dbc.mysql: DEBUG

jwt:
  secret: ${JWT_SECRET:cloudfly-production-secret-998877}
  expiration: 86400000 # 1 día en ms

evolution:
  api:
    url: ${EVOLUTION_API_URL:http://evolution_api:8080}
    key: ${EVOLUTION_API_KEY:CAMBIA_ESTA_LLAVE_LARGA_Y_UNICA}

